name: spring backend auto deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git 레포지토리 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle 빌드
        run: chmod +x ./gradlew && ./gradlew clean build

      - name: Docker 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_USER }}/spring-backend:latest .

      - name: DockerHub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Docker 이미지 푸시
        run: docker push ${{ secrets.DOCKER_USER }}/spring-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: EC2에 접속해 컨테이너 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "${{ secrets.DOCKER_KEY }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
            docker stop spring-backend || true
            docker rm -f spring-backend || true
            docker rmi ${{ secrets.DOCKER_USER }}/spring-backend:latest || true
            docker pull ${{ secrets.DOCKER_USER }}/spring-backend:latest
            docker run -d -p 8080:8080 --name spring-backend ${{ secrets.DOCKER_USER }}/spring-backend:latest
